version: "3.7"
services:
  api:
    container_name: metron_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    restart: on-failure

  db:
    image: mysql:latest
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: on-failure