version: "3.7"
services:
  api:
    container_name: metron_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports:
      - "9000:5000"
    restart: on-failure

  db:
    image: mariadb:latest
    ports:
      - "32000:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: MetronTA
      MARIADB_USER: metron
      MARIADB_PASSWORD: metron
    restart: on-failure